<?php
//$dictionary['Lead']['fields']['communication_representative_c']=
//    array (
//      'labelValue' => 'ooba Representative',
//      'dependency' => '',
//      'required' => false,
//      'source' => 'non-db',
//      'name' => 'communication_representative_c',
//      'vname' => 'LBL_COMMUNICATION_REPRESENTATIVE',
//      'type' => 'relate',
//      'massupdate' => '0',
//      'default' => NULL,
//      'no_default' => false,
//      'comments' => '',
//      'help' => '',
//      'importable' => 'true',
//      'duplicate_merge' => 'disabled',
//      'duplicate_merge_dom_value' => '0',
//      'audited' => false,
//      'reportable' => true,
//      'unified_search' => false,
//      'merge_filter' => 'disabled',
//      'calculated' => false,
//      'len' => '255',
//      'size' => '20',
//      'id_name' => 'rls01_resources_id21_c',
//      'ext2' => 'rls01_Resources',
//      'module' => 'rls01_Resources',
//      'rname' => 'name',
//      'quicksearch' => 'enabled',
//      'studio' => 'visible',
//      'id' => 'Leadscommunication_representative_c',
//      'custom_module' => 'Leads',
//    );
//    $dictionary['Lead']['fields']['rls01_resources_id21_c']=    
//    array (
//      array (
//      'required' => false,
//      'source' => 'custom_fields',
//      'name' => 'rls01_resources_id21_c',
//      'vname' => 'LBL_COMMUNICATION_REPRESENTATIVE_RLS01_RESOURCES_ID',
//      'type' => 'id',
//      'massupdate' => '0',
//      'default' => NULL,
//      'no_default' => false,
//      'comments' => '',
//      'help' => '',
//      'importable' => 'true',
//      'duplicate_merge' => 'disabled',
//      'duplicate_merge_dom_value' => '0',
//      'audited' => false,
//      'reportable' => false,
//      'unified_search' => false,
//      'merge_filter' => 'disabled',
//      'calculated' => false,
//      'len' => '36',
//      'size' => '20',
//      'id' => 'Leadsrls01_resources_id21_c',
//      'custom_module' => 'Leads',
//          )
//    ); 